name: GitHub Classroom Autograding (Entrega 1)
on: [push, pull_request, workflow_dispatch]
jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Composer install (php/)
        working-directory: php
        run: composer install --no-interaction --no-progress
      - uses: education/autograding@v1
